# Generated by Django 4.2.16 on 2026-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("pro", "Pro"), ("ultra", "Ultra")],
                        max_length=10,
                        unique=True,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "base_price_kopeks",
                    models.PositiveIntegerField(
                        verbose_name="Базовая цена за 30 дней (копейки)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Возможности (список строк)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name='Плашка "Лучший выбор"'
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
                "ordering": ["base_price_kopeks"],
            },
        ),
    ]
