# Generated by Django 4.2.16 on 2026-07-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_pricingplan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricingplan",
            options={
                "ordering": ["price_rub"],
                "verbose_name": "Тарифный план",
                "verbose_name_plural": "Тарифные планы",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="period_days",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="tier",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="base_price_kopeks",
        ),
        migrations.RemoveField(
            model_name="pricingplan",
            name="tier",
        ),
        migrations.AddField(
            model_name="payment",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.pricingplan",
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="name",
            field=models.CharField(
                default="",
                max_length=50,
                unique=True,
                verbose_name="Название тарифа",
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="period_days",
            field=models.PositiveIntegerField(default=30, verbose_name="Дней"),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="price_rub",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Цена (₽)"
            ),
        ),
        migrations.AddField(
            model_name="pricingplan",
            name="requests_limit",
            field=models.PositiveIntegerField(
                default=50, verbose_name="Лимит запросов"
            ),
        ),
        migrations.AlterField(
            model_name="pricingplan",
            name="features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Возможности"
            ),
        ),
    ]
