# Generated by Django 4.2.16 on 2026-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0003_alter_pricingplan_options_remove_payment_period_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="months",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Месяцев"
            ),
        ),
    ]
