# Generated by Django 4.2.16 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Способ оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="platega_transaction_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="ID транзакции Platega",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="telegram_payment_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="ID платежа Telegram",
            ),
        ),
    ]
