# Generated by Django 4.2.16 on 2026-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="redirect_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="URL редиректа на оплату",
            ),
        ),
    ]
