# Generated by Django 4.2.16 on 2026-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                (
                    "username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("ultra", "Ultra"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "subscription_expires",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("requests_used", models.PositiveIntegerField(default=0)),
                ("requests_limit", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователи",
            },
        ),
    ]
