# Generated by Django 4.2.16 on 2026-07-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="photo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
