# Generated by Django 4.2.16 on 2026-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_telegramuser_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="subscription_tier",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Тариф"
            ),
        ),
    ]
