# Generated by Django 4.2.16 on 2026-07-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payment_months"),
        ("users", "0003_alter_telegramuser_subscription_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="subscription_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.pricingplan",
                verbose_name="Тариф",
            ),
        ),
    ]
