# Generated by Django 4.2.16 on 2026-07-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_telegramuser_subscription_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="photo_url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Фото"
            ),
        ),
    ]
